### ISSUE TITLE
No license disclosed prevents use

### ISSUE THREAD

**Issue by cbouy** [rareylab/InteractionDrawer#1]
Hi @rareylab and thanks a lot for publishing this library, it looks awesome!

I'd be keen on trying it out but I noticed that there is no mention of a license anywhere in the repo.
Without a license, no one apart from you can legally **use**, modify, or share the software.

If this is simply an oversight (since you went through the trouble of publishing it on GitHub and sharing instructions on how to use it),  would you please consider adding a license to the repo?

Many thanks,
Cédric Bouysset

**Comment by rareylab** [comment]
Hi, 
thank you pointing that out, a license is now added.
Kind regards

**Comment by cbouy** [comment]
Great, thank you!
